
workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/ios
      - name: Preparing Web Folder
        script: |
          # Tạo thư mục www ngay tại đây
          mkdir -p www
          cp index.html www/
          cp -R assets www/ || true
      - name: Capacitor Build
        script: |
          rm -rf ios
          npx cap init "Piggy Feast" com.quyet.piggyfeast --web-dir www
          npx cap add ios
          npx cap copy
    artifacts:
      - ios/App/*.ipa
    publishing:
      email:
        recipients:
          - daovanquyet231995@gmail.com
